name: "Action 01"

inputs:
  home:
    description: "Incoming 'home' var"
    required: true
    default: "Action 01 home"

jobs:
  example_job:
    name: Pass input and secrets to my-action
    steps:
      - uses: ./.github/actions/main.yaml@master
        with:
          home: ${{ inputs.home }}
