name: action-01
on:
  #workflow_dispatch:
  workflow_call:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'
    outputs:
      output1:
        value: ${{ jobs.say_hello.outputs.output1 }}

jobs:
  say_hello:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.prepare_message.outputs.message }}
    steps:
      - id: prepare_message
        run: |
          export MESSAGE="Hello ${{ github.event.inputs.name }} from ${{ github.event.inputs.home }}. Now is $(date)"
          echo "$MESSAGE"
          echo "::set-output name=message::$MESSAGE"
